/**
 * Undercover Mode
 *
 * Phase 4.4: Undercover Mode（オプション）
 * - Anthropic痕跡削除
 * - デフォルト変更
 *
 * クリーンルーム実装の強化
 * 商用利用の準備
 */

/**
 * Undercover設定
 */
export interface UndercoverConfig {
  enabled: boolean;
  hideAnthropicReferences: boolean;
  hideClaudeReferences: boolean;
  hideAIReferences: boolean;
  customProjectName?: string;
  customAgentName?: string;
  customProviderName?: string;
  customDocumentationUrl?: string;
  obfuscateLogs: boolean;
  removeDefaultComments: boolean;
}

/**
 * 置換ルール
 */
export interface ReplacementRule {
  pattern: RegExp | string;
  replacement: string;
  description: string;
}

/**
 * Undercover Modeマネージャー
 */
export class UndercoverMode {
  private config: UndercoverConfig;
  private replacements: ReplacementRule[] = [];

  constructor(config?: Partial<UndercoverConfig>) {
    this.config = {
      enabled: false,
      hideAnthropicReferences: true,
      hideClaudeReferences: true,
      hideAIReferences: false,
      obfuscateLogs: true,
      removeDefaultComments: true,
      ...config,
    };

    this.setupReplacements();
  }

  /**
   * 置換ルールの設定
   */
  private setupReplacements(): void {
    this.replacements = [
      // Anthropic関連の置換
      {
        pattern: /Anthropic/gi,
        replacement: this.config.customProviderName || "AI Provider",
        description: "Replace Anthropic company name",
      },
      {
        pattern: /Claude/gi,
        replacement: this.config.customAgentName || "AI Assistant",
        description: "Replace Claude model name",
      },
      {
        pattern: /OpenAI/gi,
        replacement: this.config.customProviderName || "AI Provider",
        description: "Replace OpenAI company name",
      },

      // AI関連の置換（オプション）
      {
        pattern: /artificial intelligence/gi,
        replacement: "intelligent assistant",
        description: "Replace AI terminology",
      },

      // プロジェクト関連の置換
      {
        pattern: /LunaCode/gi,
        replacement: this.config.customProjectName || "Code Assistant",
        description: "Replace project name",
      },

      // ドキュメンテーション関連の置換
      {
        pattern: /github\.com\/anthropics/gi,
        replacement:
          this.config.customDocumentationUrl || "github.com/your-repo",
        description: "Replace documentation URLs",
      },
      {
        pattern: /github\.com\/yourusername\/lunacode/gi,
        replacement:
          this.config.customDocumentationUrl || "github.com/your-repo",
        description: "Replace repository URLs",
      },
    ];

    // AI参照を隠す場合
    if (this.config.hideAIReferences) {
      this.replacements.push(
        {
          pattern: /AI assistant/gi,
          replacement: "assistant",
          description: "Replace AI assistant",
        },
        {
          pattern: /AI-powered/gi,
          replacement: "smart",
          description: "Replace AI-powered",
        },
        {
          pattern: /AI-driven/gi,
          replacement: "automation-driven",
          description: "Replace AI-driven",
        },
      );
    }
  }

  /**
   * 文字列をクリーンアップ
   */
  cleanString(input: string): string {
    if (!this.config.enabled) {
      return input;
    }

    let output = input;

    // 全ての置換ルールを適用
    for (const rule of this.replacements) {
      if (rule.pattern instanceof RegExp) {
        output = output.replace(rule.pattern, rule.replacement);
      } else {
        output = output.split(rule.pattern).join(rule.replacement);
      }
    }

    // デフォルトコメントの削除
    if (this.config.removeDefaultComments) {
      output = this.removeDefaultComments(output);
    }

    // ログの難読化（オプション）
    if (this.config.obfuscateLogs) {
      output = this.obfuscateLogs(output);
    }

    return output;
  }

  /**
   * デフォルトコメントの削除
   */
  private removeDefaultComments(input: string): string {
    // Claude Code特有のコメントを削除
    const commentPatterns = [
      /# Generated by Claude Code/gi,
      /# Anthropic Claude Code/gi,
      /# Claude-inspired/gi,
      /\/\/ Claude Code generated/gi,
      /\/\/ Anthropic generated/gi,
      /\/\*.*Claude.*\*\//gi,
      /\/\*.*Anthropic.*\*\//gi,
    ];

    let output = input;
    for (const pattern of commentPatterns) {
      output = output.replace(pattern, "");
    }

    return output;
  }

  /**
   * ログの難読化
   */
  private obfuscateLogs(input: string): string {
    // 機密な情報の置換
    const sensitivePatterns = [
      {
        pattern: /sk-[a-zA-Z0-9]{20,}/gi,
        replacement: "sk-***",
        description: "Obfuscate API keys",
      },
      {
        pattern: /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/gi,
        replacement: "***@***.***",
        description: "Obfuscate email addresses",
      },
      {
        pattern: /\b\d{16}\b/g, // クレジットカード番号
        replacement: "****-****-****-****",
        description: "Obfuscate credit card numbers",
      },
    ];

    let output = input;
    for (const pattern of sensitivePatterns) {
      if (pattern.pattern instanceof RegExp) {
        output = output.replace(pattern.pattern, pattern.replacement);
      }
    }

    return output;
  }

  /**
   * 設定の更新
   */
  updateConfig(updates: Partial<UndercoverConfig>): void {
    this.config = { ...this.config, ...updates };

    // 設定が変更された場合、置換ルールを再構築
    if (
      updates.customAgentName ||
      updates.customProviderName ||
      updates.customProjectName
    ) {
      this.setupReplacements();
    }
  }

  /**
   * 設定を取得
   */
  getConfig(): UndercoverConfig {
    return { ...this.config };
  }

  /**
   * Undercoverモードを有効化
   */
  enable(): void {
    this.config.enabled = true;
    console.log("🕵️ Undercover Mode enabled");
  }

  /**
   * Undercoverモードを無効化
   */
  disable(): void {
    this.config.enabled = false;
    console.log("🔓 Undercover Mode disabled");
  }

  /**
   * 有効かどうかを確認
   */
  isEnabled(): boolean {
    return this.config.enabled;
  }

  /**
   * ファイルをクリーンアップ
   */
  async cleanFile(filePath: string): Promise<string> {
    try {
      const { readFile, writeFile } = await import("fs/promises");
      const content = await readFile(filePath, "utf-8");
      const cleanedContent = this.cleanString(content);
      await writeFile(filePath, cleanedContent, "utf-8");

      console.log(`✅ Cleaned file: ${filePath}`);

      return cleanedContent;
    } catch (error) {
      console.error(`❌ Failed to clean file ${filePath}:`, error);
      throw error;
    }
  }

  /**
   * ディレクトリをクリーンアップ
   */
  async cleanDirectory(
    directoryPath: string,
    filePattern: string = "*",
  ): Promise<number> {
    try {
      const { readdir, readFile, writeFile } = await import("fs/promises");
      const { join } = await import("path");

      const files = await readdir(directoryPath);
      let cleanedCount = 0;

      for (const file of files) {
        const filePath = join(directoryPath, file);

        // ディレクトリはスキップ
        try {
          const { stat } = await import("fs/promises");
          const fileStat = await stat(filePath);

          if (fileStat.isDirectory()) {
            continue;
          }
        } catch {
          continue;
        }

        // パターンマッチング
        if (filePattern !== "*" && !this.matchPattern(file, filePattern)) {
          continue;
        }

        try {
          const content = await readFile(filePath, "utf-8");
          const cleanedContent = this.cleanString(content);

          // 内容が変更された場合のみ書き込み
          if (content !== cleanedContent) {
            await writeFile(filePath, cleanedContent, "utf-8");
            cleanedCount++;
          }
        } catch {
          console.warn(`⚠️ Skipped file: ${filePath}`);
        }
      }

      console.log(
        `✅ Cleaned ${cleanedCount} files in directory: ${directoryPath}`,
      );

      return cleanedCount;
    } catch (error) {
      console.error(`❌ Failed to clean directory ${directoryPath}:`, error);
      throw error;
    }
  }

  /**
   * パターンマッチング
   */
  private matchPattern(filename: string, pattern: string): boolean {
    // 簡易的なglobパターンマッチング
    const regexPattern = pattern.replace(/\*/g, ".*").replace(/\?/g, ".");
    const regex = new RegExp(`^${regexPattern}$`);

    return regex.test(filename);
  }

  /**
   * コードファイルをクリーンアップ
   */
  async cleanCodeFiles(
    basePath: string,
  ): Promise<{ cleaned: number; errors: number }> {
    const { readdir, readFile, writeFile, stat } = await import("fs/promises");
    const { join } = await import("path");

    const extensions = [".ts", ".js", ".tsx", ".jsx", ".py", ".rs", ".go"];
    let cleaned = 0;
    let errors = 0;

    try {
      const files = await readdir(basePath, { recursive: true });

      for (const file of files) {
        const filePath = join(basePath, file);

        try {
          const fileStat = await stat(filePath);

          if (fileStat.isDirectory()) {
            continue;
          }

          // 拡張子のチェック
          const ext = file.substring(file.lastIndexOf("."));
          if (!extensions.includes(ext)) {
            continue;
          }

          const content = await readFile(filePath, "utf-8");
          const cleanedContent = this.cleanString(content);

          if (content !== cleanedContent) {
            await writeFile(filePath, cleanedContent, "utf-8");
            cleaned++;
          }
        } catch (error) {
          console.warn(`⚠️ Error processing file ${filePath}:`, error);
          errors++;
        }
      }
    } catch (error) {
      console.error(`❌ Error cleaning code files:`, error);
    }

    console.log(`📊 Cleaned ${cleaned} code files, ${errors} errors`);

    return { cleaned, errors };
  }

  /**
   * 置換ルールを取得
   */
  getReplacements(): ReplacementRule[] {
    return [...this.replacements];
  }

  /**
   * カスタム置換ルールを追加
   */
  addCustomReplacement(
    pattern: string | RegExp,
    replacement: string,
    description: string,
  ): void {
    this.replacements.push({ pattern, replacement, description });
  }

  /**
   * 置換ルールを削除
   */
  removeReplacement(index: number): void {
    if (index >= 0 && index < this.replacements.length) {
      this.replacements.splice(index, 1);
    }
  }

  /**
   * 現在の設定をエクスポート
   */
  exportConfig(): string {
    return JSON.stringify(this.config, null, 2);
  }

  /**
   * 設定をインポート
   */
  importConfig(configJson: string): void {
    try {
      const config = JSON.parse(configJson) as UndercoverConfig;
      this.updateConfig(config);
      console.log("✅ Imported Undercover Mode configuration");
    } catch (error) {
      console.error("❌ Failed to import configuration:", error);
    }
  }
}
